### ISSUE TITLE
Multi-language support for user interface

### ISSUE THREAD

**Issue by wcxu21** [Apollo199999999/DynaWin#2]
Hi
I am from China, can you add multi-language support to this application?
I can help you translate simplified Chinese.
Thank you for your work. ：-）

**Comment by Apollo199999999** [comment]
Hello,
As of now, it is too difficult to separate the text from the UI to add translation support. While I may consider this for a future update, I don't have much plans to do so.
I will also consider this for future apps, to separate the text from the UI for easier translation.

**Comment by wcxu21** [comment]
Thanks for your reply!
Multi-language support allows the application to have more users. Hope to add multi-language support in future versions.
If you need a Chinese translation, you can send a message to me. I will assist you to complete the Chinese translation content.
Thank u!
